//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyChat.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_messages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_messages()
        {
            this.isDelete = "N";
            this.isDeleteSender = "N";
            this.isDeleteReceiver = "N";
        }
    
        public string messageCode { get; set; }
        public int id { get; set; }
        public string chatText { get; set; }
        public string sender { get; set; }
        public string receiver { get; set; }
        public string isDelete { get; set; }
        public string isActive { get; set; }
        public string isDeleteSender { get; set; }
        public string isDeleteReceiver { get; set; }
        public System.DateTime createdAt { get; set; }
        public string senderName { get; set; }
        public string receiverName { get; set; }
    }
}
