//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyChat.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_users
    {
        public string userCode { get; set; }
        public int id { get; set; }
        public string email { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string isActive { get; set; }
        public System.DateTime createdAt { get; set; }
    }
}
